### ISSUE TITLE
snowflake connector warn

### ISSUE THREAD

**Issue by odinuv** [keboola/python-transformation#2]
lock directory: /root/.cache/snowflake/ocsp_response_cache.json.lck, error: [Errno 2] No such file or directory: '/root/.cache/snowflake/ocsp_response_cache.json'

**Comment by ondrejhlavacek** [comment]
jak se ti to povedlo?

**Comment by odinuv** [comment]
me nijak, je to v tom jobu cos linkoval, prepdokladam, ze o nic nejde a bude stacit vytvoreni toho adresare v imagi

**Comment by ondrejhlavacek** [comment]
kua, toho jsem si vůbec nevšiml!

**Comment by odinuv** [comment]
fixed in 8c3c8ed4c054e42661c6a93857d4d4a86ce93694
