### ISSUE TITLE
Internal error on expired file from input

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/python-transformation#5]
Nevím teda jestli to nepatří obecně do transformací nebo dokonce do docker runneru, ale vyfailovalo mi to tady. Nastavil jsem transformaci s labelem na files:
![image](https://user-images.githubusercontent.com/215660/56153654-fcb64100-5fb6-11e9-9b16-c0e8a8ab490c.png)
Pod labelem jsou ale jen samý vyexpirovaný soubory:
![image](https://user-images.githubusercontent.com/215660/56153724-1c4d6980-5fb7-11e9-8740-de3f66de224e.png)
A transformace vyfailuje s internal errorem:
<img width="472" alt=" Job 496734245 2019-04-15 19-47-41" src="https://user-images.githubusercontent.com/215660/56153834-59196080-5fb7-11e9-9d04-149b44dbf480.png">

Druhá věc, která s tím asi nesouvisí, je, že pod tím exceptionId (`transformation-6af7d2b8340c7d03378d69e78225e8c3`) nedohledám co se stalo, tam je taky jen `internal error occured`. Dozvěděl jsem se to náhodou z #docker-notifications a je to pod `docker-c5da90a50daadd9ea89c5cda4cdc58b5` a chyba teda je: `Failed to download file out.c-main.products.csv 485855066`. Tzn. legálně se na input dostal expirovaný soubor.

**Comment by odinuv** [comment]
duplicate of https://github.com/keboola/docker-bundle/issues/384
duplicate of https://github.com/keboola/input-mapping/issues/18
duplicate of https://github.com/keboola/connection/issues/1080

:)
